# Generated by Django 2.1.7 on 2019-04-05 01:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20190404_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='image',
            field=models.FileField(default=django.utils.timezone.now, upload_to='img/'),
            preserve_default=False,
        ),
    ]
