# Generated by Django 2.1.7 on 2019-04-05 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20190404_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(height_field=100, upload_to='portfolio/static/img', width_field=100),
        ),
    ]
