# Generated by Django 2.1.7 on 2019-04-05 04:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_auto_20190404_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='image',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='picture',
            field=models.FileField(default=django.utils.timezone.now, upload_to='portfolio/static/img'),
            preserve_default=False,
        ),
    ]
