# Generated by Django 2.1.7 on 2019-04-05 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_auto_20190404_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='picture',
            new_name='image',
        ),
    ]
