# Generated by Django 2.1.7 on 2019-04-05 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_auto_20190405_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='portfolio/static/img', width_field='width_field'),
        ),
    ]
