# Generated by Django 2.1.7 on 2019-04-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_auto_20190405_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='static/img', width_field='width_field'),
        ),
    ]
