# Generated by Django 2.1.7 on 2019-04-05 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0024_auto_20190405_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='mesage',
            new_name='message',
        ),
    ]
