# Generated by Django 2.1.7 on 2019-04-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0026_services_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='text',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='name',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='site',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='services',
            name='message',
            field=models.TextField(default=''),
        ),
    ]
