# Generated by Django 2.1.7 on 2019-04-05 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0027_auto_20190405_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='color',
            new_name='background',
        ),
    ]
